name: crispr-screen-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - matplotlib
  - scipy
  - cutadapt
  - mageck=0.5.9.5
  - parallel
  - jq
  - libnsl
  - r-base=4.4
  - r-ggplot2
  - r-dplyr
  - r-data.table
  - r-scales
  - bioconductor-org.mm.eg.db=3.20.0
  - bioconductor-clusterprofiler=4.14.0
  - bioconductor-mageckflute=2.9.0
  - pip
